import Link from 'next/link'

export const metadata = { title: 'Terms · Fr. Pimen Calendar' }

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white text-neutral-900">
      <main className="max-w-2xl mx-auto px-5 py-10">
        <Link href="/" className="text-sm text-neutral-500 hover:text-neutral-900">← Back</Link>
        <h1 className="text-3xl font-bold mt-4">Terms of Use</h1>
        <p className="text-sm text-neutral-500 mt-1">Last updated: April 2026</p>

        <div className="mt-6 space-y-5 text-[15px] leading-relaxed text-neutral-700">
          <section>
            <h2 className="font-semibold text-neutral-900 text-lg mb-1.5">1. Single-user license</h2>
            <p>This application is licensed for use by one named priest only. Do not share login credentials or grant access to others outside the calendar-sharing feature.</p>
          </section>

          <section>
            <h2 className="font-semibold text-neutral-900 text-lg mb-1.5">2. No warranty</h2>
            <p>The app is provided as-is. The operator makes no guarantees about uptime, data preservation, or fitness for any particular purpose. Always keep an independent backup of critical schedule information.</p>
          </section>

          <section>
            <h2 className="font-semibold text-neutral-900 text-lg mb-1.5">3. AI assistant</h2>
            <p>The chat assistant uses Anthropic Claude to answer questions about your calendar. Responses are generated by AI and may occasionally be incorrect. Verify any consequential information against the calendar itself.</p>
          </section>

          <section>
            <h2 className="font-semibold text-neutral-900 text-lg mb-1.5">4. Acceptable use</h2>
            <p>Do not use the app to harm others, send spam, or violate any applicable law.</p>
          </section>

          <section>
            <h2 className="font-semibold text-neutral-900 text-lg mb-1.5">5. Termination</h2>
            <p>The operator may suspend or terminate access at any time. You may stop using the app at any time and request data deletion.</p>
          </section>

          <section>
            <p className="text-xs text-neutral-500 italic">These templates are provided as a starting point. Have a qualified attorney review them before relying on them in production.</p>
          </section>
        </div>
      </main>
    </div>
  )
}
